"""initial commit

Revision ID: 2ef296473c43 Revises: Create Date: 2026-03-02 10:50:48.394889

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ef296473c43"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_consent",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("requested_by", sa.String(length=32), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "polls",
        sa.Column("poll_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended", sa.String(length=1), nullable=True),
        sa.Column("summary_message_ts", sa.String(length=32), nullable=True),
        sa.Column("summary_message_channel", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("poll_id"),
    )
    op.create_table(
        "profile_changes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=2048), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("description_edited_by", sa.String(length=32), nullable=True),
        sa.Column("description_edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notification_channel", sa.String(length=32), nullable=True),
        sa.Column("notification_ts", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_profile_changes_timestamp"),
        "profile_changes",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profile_changes_user_id"), "profile_changes", ["user_id"], unique=False
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "watched_users",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "poll_candidates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("poll_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("message_ts", sa.String(length=32), nullable=True),
        sa.Column("message_channel", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["poll_id"], ["polls.poll_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("poll_id", "user_id", name="uq_poll_candidate"),
    )
    op.create_index(
        "ix_poll_candidates_poll_id", "poll_candidates", ["poll_id"], unique=False
    )
    op.create_table(
        "poll_candidate_pictures",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("poll_candidate_id", sa.Integer(), nullable=False),
        sa.Column("avatar_url", sa.String(length=2048), nullable=False),
        sa.Column("duration", sa.String(length=32), nullable=False),
        sa.Column("week", sa.String(length=16), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("description_edited_by", sa.String(length=32), nullable=True),
        sa.Column("description_edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["poll_candidate_id"], ["poll_candidates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_poll_candidate_pictures_candidate_id",
        "poll_candidate_pictures",
        ["poll_candidate_id"],
        unique=False,
    )
    op.create_table(
        "votes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("poll_id", sa.String(length=64), nullable=False),
        sa.Column("voter_id", sa.String(length=32), nullable=False),
        sa.Column("picture_id", sa.Integer(), nullable=False),
        sa.Column("voted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["picture_id"], ["poll_candidate_pictures.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["poll_id"], ["polls.poll_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "poll_id", "voter_id", "picture_id", name="uq_vote_picture"
        ),
    )
    op.create_index(
        "ix_votes_picture", "votes", ["poll_id", "picture_id"], unique=False
    )
    op.create_index("ix_votes_poll_id", "votes", ["poll_id"], unique=False)
    op.create_index("ix_votes_voter", "votes", ["poll_id", "voter_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_votes_voter", table_name="votes")
    op.drop_index("ix_votes_poll_id", table_name="votes")
    op.drop_index("ix_votes_picture", table_name="votes")
    op.drop_table("votes")
    op.drop_index(
        "ix_poll_candidate_pictures_candidate_id", table_name="poll_candidate_pictures"
    )
    op.drop_table("poll_candidate_pictures")
    op.drop_index("ix_poll_candidates_poll_id", table_name="poll_candidates")
    op.drop_table("poll_candidates")
    op.drop_table("watched_users")
    op.drop_table("settings")
    op.drop_index(op.f("ix_profile_changes_user_id"), table_name="profile_changes")
    op.drop_index(op.f("ix_profile_changes_timestamp"), table_name="profile_changes")
    op.drop_table("profile_changes")
    op.drop_table("polls")
    op.drop_table("pending_consent")
    # ### end Alembic commands ###
